plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nebula.launcher'
    compileSdk 34

    defaultConfig {
        applicationId "com.nebula.launcher"
        minSdk 21
        targetSdk 34
        versionCode 4
        versionName "1.4.0"
        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
        }
    }

    packagingOptions {
        // 内置 JRE/渲染栈 so 全部解压到 nativeLibraryDir
        jniLibs {
            useLegacyPackaging = true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
        coreLibraryDesugaringEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.create("nebula") {
                storeFile file("../nebula-release.keystore")
                storePassword "nebula123"
                keyAlias "nebula"
                keyPassword "nebula123"
            }
        }
    }
}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.4'
}
