plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nebula.launcher'
    compileSdk 34

    defaultConfig {
        applicationId "com.nebula.launcher"
        minSdk 21
        targetSdk 34
        versionCode 2
        versionName "1.2.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.create("nebula") {
                storeFile file("../nebula-release.keystore")
                storePassword "nebula123"
                keyAlias "nebula"
                keyPassword "nebula123"
            }
        }
    }
}
